Add step to ensure yarn is installed in yml file

diff --git a/.azure/run-playwright-e2e-tests.yml b/.azure/run-playwright-e2e-tests.yml
--- a/.azure/run-playwright-e2e-tests.yml
+++ b/.azure/run-playwright-e2e-tests.yml
@@ -57,6 +57,16 @@ steps:
     displayName: 'Install Node.js'
 
   - script: |
+      if ! command -v yarn &> /dev/null
+      then
+        echo "Yarn not found. Installing..."
+        npm install --global yarn
+      else
+        echo "Yarn already installed."
+      fi
+    displayName: 'Ensure Yarn is installed'    
+
+  - script: |
       yarn install
       yarn setup
     displayName: 'Install dependencies and Playwright browsers'
